"""Quantised PyTorch model -> integer Graph -> .sfm / C header."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .graph import ACT_LINEAR, ACT_RAW, ACT_RELU1, Conv2d, Dense, GlobalAvgPool, Graph
from .sfm import dumps

_ACTS = {"relu1": ACT_RELU1, "linear": ACT_LINEAR, "raw": ACT_RAW}


def to_graph(model, input_shape=None, labels=None, name=None) -> Graph:
    """Walk a chain of SF layers (see models.SFChain) and emit integer ops."""
    import torch.nn as nn

    from .qat import SFConv2d, SFGlobalAvgPool, SFLinear

    input_shape = tuple(input_shape or model.input_shape)
    labels = list(labels if labels is not None else getattr(model, "labels", []))
    name = name or getattr(model, "model_name", type(model).__name__)
    ops = []
    for m in model.children() if isinstance(model, nn.Sequential) else [model]:
        if isinstance(m, SFConv2d):
            if not bool(m.quantized):
                raise ValueError("model is still in the float phase; call quantize_model first")
            w, b, e = m.integer_params()
            c = m.conv
            if c.dilation != (1, 1) or c.padding[0] != c.padding[1] or c.stride[0] != c.stride[1]:
                raise ValueError("runtime supports square stride/padding and no dilation")
            ops.append(Conv2d(
                weight=w.permute(0, 2, 3, 1).contiguous().numpy(),  # OIHW -> O,H,W,I
                bias=b.numpy(), stride=c.stride[0], pad=c.padding[0], groups=c.groups,
                gain_exp=e, act=_ACTS[m.act], wbits=m.wbits))
        elif isinstance(m, SFLinear):
            if not bool(m.quantized):
                raise ValueError("model is still in the float phase; call quantize_model first")
            w, b, e = m.integer_params()
            ops.append(Dense(weight=w.numpy(), bias=b.numpy(), gain_exp=e,
                             act=_ACTS[m.act], wbits=m.wbits))
        elif isinstance(m, SFGlobalAvgPool):
            ops.append(GlobalAvgPool())
        elif isinstance(m, (nn.Identity, nn.Dropout)):
            continue
        else:
            raise TypeError(f"cannot export {type(m).__name__}")
    graph = Graph(input_shape, ops, labels=labels, name=name)
    graph.validate()
    return graph


def logits_scale(graph: Graph) -> float:
    """Real value of one unit of the raw int32 output."""
    last = graph.ops[-1]
    return 2.0 ** last.gain_exp / (128.0 * 128.0)


def to_c_header(data: bytes, symbol: str) -> str:
    """Embed .sfm bytes as a 4-byte aligned const array (lands in MCU flash)."""
    lines = [
        "/* Generated by sfedge.export; do not edit. */",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"static const size_t {symbol}_len = {len(data)};",
        f"static const uint8_t {symbol}[{len(data)}] __attribute__((aligned(4))) = {{",
    ]
    arr = np.frombuffer(data, np.uint8)
    for i in range(0, len(arr), 16):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in arr[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def export(model, out_path, header_symbol=None) -> Graph:
    """Write <out>.sfm, and <out>.h too when header_symbol is given."""
    graph = to_graph(model)
    data = dumps(graph)
    out_path = Path(out_path)
    out_path.write_bytes(data)
    if header_symbol:
        out_path.with_suffix(".h").write_text(to_c_header(data, header_symbol))
    return graph
